version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "<TASK_DEFINITION>"
       LoadBalancerInfo:
         ContainerName: blue-green-nodejs
         ContainerPort: 3000
       PlatformVersion: 1.4.0
#       NetworkConfiguration:
#         awsvpcConfiguration:
#           subnets:
#           securityGroups:
#           assignPublicIp: DISABLED

 #Hooks:
 #    - AfterAllowTestTraffic: "LambdaFunction..."
 #    - AfterInstall: "LambdaFunction..."
 #    - AfterAllowTestTraffic: "LambdaFunction..."
 #    - BeforeAllowTraffic: "LambdaFunction..."
 #    - AfterAllowTraffic: "LambdaFunction..."
